# Generated by Django 4.0.9 on 2023-03-03 16:49

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('representative_name', models.CharField(default='', max_length=100)),
                ('members', models.ManyToManyField(blank=True, related_name='teams_members', to='participants.participants')),
            ],
        ),
    ]
